---

### Perform the initial system configuration on Debian-based systems ###

- name: Install aptitude
  apt:
    name: aptitude
    state: present

- name: Update and upgrade all packages
  apt:
    upgrade: full
    update_cache: true
  when: upgrade is defined and upgrade in ["true", "yes", "y"]
  notify:
    restart server
  tags:
    - upgrade_server

- name: Install handy and necessary packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - nmap
    - curl
    - lsof
    - acl
    - software-properties-common

- name: Generate danish locale
  locale_gen:
    name: da_DK.UTF-8
    state: present
  tags:
    - locale_gen

- name: Setting the locale to da_DK.UTF-8
  copy:
    src: locale.conf
    dest: /etc/default/locale

- name: Install ntp
  apt:
    name: ntp
    state: present
